### ISSUE TITLE
dataverse.org/metrics showing 0 contributors

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse-metrics#28]
https://dataverse.org/metrics is showing we have no contributors. We have more than that. :) 

<img width="636" alt="Screen Shot 2019-06-27 at 12 33 12 PM" src="https://user-images.githubusercontent.com/7773392/60283694-cc085700-98d7-11e9-9e08-77caa1e0d6a5.png">

**Comment by djbrooke** [comment]
This is working as expected now. Closing.

**Comment by pdurbin** [comment]
For the record, we didn't fix anything. This problem is intermittent. Better error handling (#26) would help.
