### ISSUE TITLE
Datasets by Most Common Subject: #3 is null

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-metrics#37]
on https://dataversemetrics.odum.unc.edu/dataverse-metrics:

![Screen Shot 2019-11-12 at 15 20 28](https://user-images.githubusercontent.com/12831666/68707557-fa719080-055f-11ea-835b-843da6ce408e.png)

**Comment by qqmyers** [comment]
It says "Medicine, Health and Life Sciences" when I look now. Has this been fixed and not closed?

**Comment by pdurbin** [comment]
I don't think we did anything to fix it but I agree that it's no longer an issue. No more donut hole.

**Comment by qqmyers** [comment]
OK - closing (still fixed today)
