### ISSUE TITLE
Dataverse metrics are not accessible

### ISSUE THREAD

**Issue by juancorr** [IQSS/dataverse-metrics#68]
Dataverse metrics page is not working (Wednesday, September 29, 2021. 10:55 GMT) : https://dataverse.org/metrics

The https://d3plus.org/js/d3.js and https://d3plus.org/js/d3plus.js javascript files are not available.

**Comment by qqmyers** [comment]
Thanks for the heads up! 

Looks like d3plus v2 has come out and the v1.x libraries are no longer hosted. I did a quick check and using 2.0 will require some code changes, so - in the newmetrics branch, I switched to using a local copy of the v1.9.8 d3 and d3plus libraries (see commit https://github.com/IQSS/dataverse-metrics/pull/52/commits/0e3a91d9f1c1f8dbc5f4ddbdf439cbbe65038d42). Those same changes could be applied to the base branch for use at dataverse.org/metrics.

**Comment by juancorr** [comment]
Thanks to you,
  We have updated our metrics with the new libraries.
  https://edatos.consorciomadrono.es/metrics.xhtml
Juan Corrales

**Comment by donsizemore** [comment]
Thanks to @qqmyers I dropped his local copy of d3plus v1.9.8 on the Dataverse Metrics page. Vote to close.

**Comment by juancorr** [comment]
Dataverse metrics site is working again and I have checked the code in e-cienciaDatos.

I am going to close it.
