### ISSUE TITLE
open links in new tabs

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-metrics#8]
I think we have a consensus on opening institution links in a new tab/window. PR forthcoming.

**Comment by pdurbin** [comment]
@mheppler and suggested that all links should be opened in a new tab and @donsizemore pushed 09be14c to fix this. Thanks!

**Comment by pdurbin** [comment]
@donsizemore thanks for pull request #9 . I just confirmed that all the links open in a new tab, merged the pull request, and cut a new v0.2.1 release: https://github.com/IQSS/dataverse-metrics/releases/tag/v0.2.1
