### ISSUE TITLE
Show names of subdataverses (collections) instead of the aliases in the tree and header

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse-metrics#86]
Currently in the local metrics the tree (collection selection) and the header (sub-title) show the alias, which is great for URLs but not very nice for readability, The name should be used instead. 
The JSON response from the tree API endpoint contains this 'name' besides the 'alias', so it could be used without any extra HPPT calls.

**Comment by qqmyers** [comment]
Closed by #87
